[package]
name = "esr-lexicon"
version = "0.1.0"
authors = ["Mathis EON <eon@abes.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.10.4", features = ["json"] }
tokio = { version = "0.2.14", features = ["full"] }
serde = { version = "1.0.105", features = ["derive"] }
serde_json = "1.0.50"
env_logger = "0.7.1"
log = "0.4.8"
<<<<<<< HEAD
jq-rs = { version = "0.4.1", features = ["bundled"] }
=======
jq-rs = "0.4.1"
>>>>>>> def610ea4cf00c34b9272ff3bc5beb36c2cafb69
clap = "2.33.0"
futures = "0.3.4"

[dev-dependencies]
tempfile = "3.1.0"

[profile.release]
opt-level = 3
